name: Python test run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.7, 3.8.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      env:
        POETRY_VIRTUALENVS_CREATE: false
      run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source ~/.profile
          source ~/.bash_profile
          poetry --version
    - name: Install dependencies
      env:
        POETRY_VIRTUALENVS_CREATE: false
      run: |
          source ~/.profile
          source ~/.bash_profile
          poetry install --no-root
    - name: Test with pytest
      run: |
          pytest
